### ISSUE TITLE
USER STORY: Breadcrumb Navigation

### ISSUE THREAD

**Issue by TimRas** [TimRas/Fit-For-All#44]
As a **user** I want to be able to **be able to easily navigate back and forth through pages** so that I can **have a clear understanding of where I am on the application**

- [x] Add bootstrap breadcrumb html to each respective page
- [x] Fill in all variables needed to trial back on each respective page
- [x]  Add css

**Comment by Mtendekuyokwa19** [comment]
Would you please describe you problem more details. Would love to contribute to this
